// SPDX-License-Identifier: GPL-3.0-only
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { unzipSync, strFromU8 } from 'fflate';
import { defaultProject } from '../../src/domain/project';

test('thread chamfer follows pitch, preserves custom values, roundtrips exports and migrates old designs', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('./'); await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 60000 });
  await page.getByRole('button', { name: 'M 型内螺纹', exact: true }).click();
  await expect(page.getByTestId('thread-chamfer')).toBeChecked();
  await expect(page.getByTestId('chamfer-size')).toHaveText('1.20 mm / 45°');
  await page.getByLabel('螺距 P', { exact: true }).fill('0.75');
  await expect(page.getByTestId('chamfer-size')).toHaveText('0.90 mm / 45°');
  await page.getByLabel('我已确认实际配合件的外径与螺距').check();
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await page.getByRole('combobox', { name: '倒角尺寸模式' }).selectOption('custom');
  await page.getByLabel('倒角尺寸 C（深度 / 径向增量）', { exact: true }).fill('0.5');
  await expect(page.getByTestId('chamfer-size')).toHaveText('0.50 mm / 45°');
  await page.getByRole('combobox', { name: '倒角尺寸模式' }).selectOption('pitch');
  await expect(page.getByTestId('chamfer-size')).toHaveText('0.90 mm / 45°');
  await page.getByRole('combobox', { name: '倒角尺寸模式' }).selectOption('custom');
  await expect(page.getByLabel('倒角尺寸 C（深度 / 径向增量）', { exact: true })).toHaveValue('0.5');
  await page.getByTestId('thread-chamfer').uncheck();
  await expect(page.getByTestId('chamfer-size')).toHaveCount(0);
  await page.getByRole('button', { name: '↶ 撤销', exact: true }).click(); await expect(page.getByTestId('thread-chamfer')).toBeChecked();
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByTestId('thread-chamfer')).toHaveAccessibleName('Thread entry lead-in chamfer');
  await page.reload(); await expect(page.getByTestId('model-status')).toContainText('Model ready', { timeout: 30000 });
  await expect(page.getByTestId('chamfer-size')).toHaveText('0.50 mm / 45°');
  await page.getByTestId('accept-warnings').check();
  for (const format of ['step', 'stl'] as const) {
    const pending = page.waitForEvent('download'); await page.getByTestId(`export-${format}`).click();
    const file = await pending; expect(file.suggestedFilename()).toContain('C0.50-45deg');
    const zip = unzipSync(readFileSync((await file.path())!));
    const p = JSON.parse(strFromU8(zip[Object.keys(zip).find(n => n.endsWith('.json'))!]));
    expect(p.schemaVersion).toBe(5); expect(p.central.thread.chamfer).toEqual({ enabled: true, mode: 'custom', sizeMm: 0.5 });
    expect(strFromU8(zip['THREAD-ENTRY.txt'])).toContain('fixed 45 degrees');
    expect(Object.keys(zip).some(n => n.endsWith(`.${format}`))).toBe(true);
  }
  await page.screenshot({ path: testInfo.outputPath('thread-chamfer.png'), fullPage: true });
  const before = await page.evaluate(() => JSON.parse(localStorage.getItem('lensboard-project-v1')!));
  await page.getByLabel('Chamfer C (depth / radial increase)', { exact: true }).fill('2.5');
  await expect(page.getByRole('alert')).toContainText('C below the thread'); await expect(page.getByTestId('export-step')).toBeDisabled();
  const old = structuredClone(before); old.schemaVersion = 3; delete old.central.thread.chamfer; delete old.boardSource; delete old.customBoard;
  page.once('dialog', dialog => dialog.accept());
  await page.locator('input[type=file]').setInputFiles({ name: 'legacy-v3.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(old)) });
  await expect(page.getByTestId('thread-chamfer')).not.toBeChecked();
  await expect(page.getByTestId('model-status')).toContainText('Model ready', { timeout: 30000 });
  expect(errors).toEqual([]);
});

test('ALPA cap hole60 and M65 use end-face protection after JSON import and export', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('./');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 60000 });
  for (const mode of ['plain', 'thread'] as const) {
    const p = defaultProject(); p.templateId = 'alpa-blank'; p.orientation.frontBack = true;
    p.relief = { ...p.relief, enabled: true, width: 80, height: 80, radius: 8, diameter: 50, angle: 90 };
    p.central.diameter = 60; p.central.mode = mode; p.central.thread.confirmed = mode === 'thread';
    page.once('dialog', dialog => dialog.accept());
    await page.locator('input[type=file]').setInputFiles({ name: `alpa-${mode}.json`, mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(p)) });
    await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
    await expect(page.getByRole('alert')).toHaveCount(0);
    await expect(page.locator('.metrics-panel')).toContainText('2.50 mm');
    await page.getByTestId('accept-warnings').check();
    const pending = page.waitForEvent('download'); await page.getByTestId('export-step').click();
    const file = await pending, zip = unzipSync(readFileSync((await file.path())!));
    const json = JSON.parse(strFromU8(zip[Object.keys(zip).find(n => n.endsWith('.json'))!]));
    expect(json.central.mode).toBe(mode); expect(json.generatorVersion).toBe('0.3.1');
    expect(json.relief.width).toBe(80); expect(Object.keys(zip).some(n => n.endsWith('.step'))).toBe(true);
  }
  // Turning relief off must NOT exempt a 60 mm hole in the original ALPA board.
  await page.locator('.relief-panel summary').click(); await page.getByTestId('relief-enabled').uncheck();
  await expect(page.getByRole('alert')).toContainText('模板保护区');
  await expect(page.getByTestId('export-step')).toBeDisabled();
  expect(errors).toEqual([]);
});

test('size-only relief accepts nonuniform templates and blocks only out-of-board base dimensions', async ({ page }) => {
  await page.goto('./');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 60000 });
  await page.locator('.relief-panel summary').click(); await page.getByTestId('relief-enabled').check();
  for (const id of ['linhof-blank', 'cambo-twr54-simplified-blank']) {
    await page.getByRole('combobox', { name: '镜头板模板' }).selectOption(id);
    await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
    await expect(page.getByRole('alert')).toHaveCount(0);
    await expect(page.locator('.manufacturing-note')).toContainText('不检查区域内的厚度');
  }
  await page.getByLabel('基座外长', { exact: true }).fill('100');
  await expect(page.getByRole('alert')).toContainText('基座外尺寸超出镜头板');
  await expect(page.getByTestId('export-step')).toBeDisabled();
  await page.getByLabel('基座外长', { exact: true }).fill('60');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await page.getByRole('combobox', { name: '基座类型' }).selectOption('circle');
  await page.getByLabel('基座外径', { exact: true }).fill('100');
  await expect(page.getByRole('alert')).toContainText('基座外尺寸超出镜头板');
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Base outer dimensions exceed');
});

test('template flips rebuild exports, preserve final coordinates, undo, reset and world axes', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('./');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 60000 });
  await expect(page.getByTestId('world-axes')).toHaveAttribute('aria-label', '世界坐标轴 · +Z 正面');
  await page.getByRole('combobox', { name: '镜头板模板' }).selectOption('alpa-blank');
  await page.locator('.relief-panel summary').click(); await page.getByTestId('relief-enabled').check();
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await page.getByTestId('template-front-back').check(); await page.getByTestId('template-up-down').check();
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('lensboard-project-v1')!));
  expect(stored.orientation).toEqual({ frontBack: true, upDown: true });
  await page.getByTestId('accept-warnings').check();
  const pending = page.waitForEvent('download'); await page.getByTestId('export-step').click();
  const downloaded = await pending, zip = unzipSync(readFileSync((await downloaded.path())!));
  const json = JSON.parse(strFromU8(zip[Object.keys(zip).find(n => n.endsWith('.json'))!]));
  expect(json.orientation).toEqual(stored.orientation); expect(json.schemaVersion).toBe(5);
  await page.getByRole('button', { name: '↶ 撤销', exact: true }).click();
  await expect(page.getByTestId('template-front-back')).toBeChecked(); await expect(page.getByTestId('template-up-down')).not.toBeChecked();
  await page.getByRole('button', { name: '↷ 重做', exact: true }).click(); await expect(page.getByTestId('template-up-down')).toBeChecked();
  await page.reload(); await expect(page.getByTestId('template-front-back')).toBeChecked(); await expect(page.getByTestId('template-up-down')).toBeChecked();
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await page.getByRole('button', { name: '立体', exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath('flipped-world-axes.png'), fullPage: true });
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByLabel('Flip front / back', { exact: true })).toBeChecked();
  await expect(page.getByTestId('world-axes')).toHaveAttribute('aria-label', 'World axes · +Z front');
  await page.getByRole('combobox', { name: 'Lensboard template' }).selectOption('sinar-blank');
  await expect(page.getByTestId('template-front-back')).not.toBeChecked(); await expect(page.getByTestId('template-up-down')).not.toBeChecked();
  await expect(page.getByTestId('model-status')).toContainText('Model ready', { timeout: 30000 });
  expect(errors).toEqual([]);
});

test('relief controls, end-face machining, edges and schema 1 migration', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('./');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 60000 });
  await expect(page.getByTestId('show-edges')).toBeChecked();
  const before = await page.evaluate(() => localStorage.getItem('lensboard-project-v1'));
  await page.getByTestId('show-edges').uncheck();
  expect(await page.evaluate(() => localStorage.getItem('lensboard-project-v1'))).toBe(before);
  await page.getByTestId('show-edges').check();
  await page.locator('.relief-panel summary').click();
  await page.getByTestId('relief-enabled').check();
  await expect(page.getByLabel('间距（+凸 / −凹）')).toHaveValue('17');
  await expect(page.getByLabel('壁厚（法向，向内）')).toHaveValue('2');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await expect(page.locator('.metrics-panel')).toContainText('2.50 mm');
  await page.getByRole('button', { name: '侧面', exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath('raised-side.png'), fullPage: true });
  await page.getByRole('button', { name: '立体', exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath('raised-iso.png'), fullPage: true });
  await page.getByLabel('间距（+凸 / −凹）').fill('-17');
  await page.getByRole('combobox', { name: '基座类型' }).selectOption('circle');
  await page.getByLabel('壁倾角', { exact: true }).fill('90');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await page.screenshot({ path: testInfo.outputPath('recessed-iso.png'), fullPage: true });
  await page.getByTestId('accept-warnings').check();
  const event = page.waitForEvent('download'); await page.getByTestId('export-step').click();
  const file = await event; const path = testInfo.outputPath('relief-step.zip'); await file.saveAs(path);
  expect(file.suggestedFilename()).toContain('recessed-17mm');
  const zip = unzipSync(readFileSync(path)), json = JSON.parse(strFromU8(zip[Object.keys(zip).find(k => k.endsWith('.json'))!]));
  expect(json.schemaVersion).toBe(5); expect(json.generatorVersion).toBe('0.3.1');
  expect(json.relief).toMatchObject({ enabled: true, spacing: -17, shape: 'circle', angle: 90 });
  await page.getByLabel('名义孔径', { exact: true }).fill('54');
  await expect(page.getByRole('alert')).toContainText('超出端面内腔');
  await expect(page.getByTestId('export-step')).toBeDisabled();
  await page.getByLabel('名义孔径', { exact: true }).fill('34.6');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await page.getByLabel('间距（+凸 / −凹）').fill('0');
  await expect(page.getByRole('alert')).toContainText('凸 / 凹板尺寸无效');
  await expect(page.getByTestId('export-step')).toBeDisabled();
  const legacy = JSON.parse(before!); delete legacy.relief; delete legacy.orientation; delete legacy.central.thread.chamfer; delete legacy.boardSource; delete legacy.customBoard; legacy.schemaVersion = 1; legacy.generatorVersion = '0.1.0';
  page.once('dialog', dialog => dialog.accept());
  await page.locator('input[type=file]').setInputFiles({ name: 'legacy.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(legacy)) });
  await expect(page.getByTestId('relief-enabled')).not.toBeChecked();
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('lensboard-project-v1')!));
  expect(stored.schemaVersion).toBe(5); expect(stored.boardSource).toBe('template'); expect(stored.central.diameter).toBe(34.6); expect(stored.central.thread.chamfer.enabled).toBe(false);
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByTestId('relief-enabled')).toHaveAccessibleName('Enable raised / recessed board');
  expect(errors).toEqual([]);
});

test('dark theme defaults despite light system, persists independently, and Report targets project issues', async ({ page }, testInfo) => {
  await page.emulateMedia({ colorScheme: 'light' });
  await page.addInitScript(() => {
    (window as unknown as { cadBuilds: number }).cadBuilds = 0;
    const original = Worker.prototype.postMessage;
    Worker.prototype.postMessage = function(message: unknown, ...rest: unknown[]) {
      if ((message as { type?: string })?.type === 'build') (window as unknown as { cadBuilds: number }).cadBuilds++;
      return Reflect.apply(original, this, [message, ...rest]);
    };
  });
  await page.goto('./');
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await expect(page.getByTestId('theme-toggle')).toHaveAccessibleName('切换为亮色主题');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 60000 });
  const before = await page.evaluate(() => ({ builds: (window as unknown as { cadBuilds: number }).cadBuilds, project: localStorage.getItem('lensboard-project-v1') }));
  await expect(page.getByTestId('report-link')).toHaveAttribute('href', 'https://github.com/RayforLoy/LensboardGenerator/issues');
  await expect(page.getByTestId('report-link')).toHaveAttribute('target', '_blank');
  await expect(page.getByTestId('report-link')).toHaveAttribute('rel', 'noopener noreferrer');
  await page.screenshot({ path: testInfo.outputPath('dark-studio.png'), fullPage: true });
  await page.getByTestId('show-edges').uncheck();
  await page.getByTestId('show-edges').check();
  await page.getByTestId('theme-toggle').click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await expect(page.getByTestId('theme-toggle')).toHaveAccessibleName('切换为暗色主题');
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByTestId('theme-toggle')).toHaveAccessibleName('Switch to dark theme');
  expect(await page.evaluate(() => ({ builds: (window as unknown as { cadBuilds: number }).cadBuilds, project: localStorage.getItem('lensboard-project-v1') }))).toEqual(before);
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await expect(page.getByTestId('theme-toggle')).toHaveAccessibleName('Switch to dark theme');
  await page.getByTestId('theme-toggle').click();
  await page.getByLabel('X offset', { exact: true }).first().fill('100');
  await expect(page.getByRole('alert')).toContainText('protected', { timeout: 30000 });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('dark-mobile.png'), fullPage: true });
});

test('Chinese default, actual CAD, print allowance, language persistence and ZIP export', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('./');
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('大画幅镜头板工作室');
  await expect(page.getByTestId('print-checkbox')).not.toBeChecked();
  await expect(page.getByTestId('actual-diameter')).toHaveText('34.60 mm');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 60000 });
  await page.getByTestId('print-checkbox').check();
  await expect(page.getByTestId('actual-diameter')).toHaveText('35.10 mm');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await page.getByRole('combobox', { name: '快门孔径预设' }).selectOption('copal-3');
  await expect(page.getByTestId('actual-diameter')).toHaveText('65.50 mm');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Large-format Lensboard Studio');
  await expect(page.getByTestId('actual-diameter')).toHaveText('65.50 mm');
  await page.reload();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Large-format Lensboard Studio');
  await expect(page.getByTestId('model-status')).toContainText('Model ready', { timeout: 60000 });
  await expect(page.getByTestId('export-step')).toBeDisabled();
  await page.getByTestId('accept-warnings').check();
  const event = page.waitForEvent('download'); await page.getByTestId('export-step').click();
  const file = await event; const path = testInfo.outputPath('model-step.zip'); await file.saveAs(path);
  const zip = unzipSync(readFileSync(path));
  expect(Object.keys(zip).some(k => k.endsWith('.step'))).toBe(true);
  expect(Object.keys(zip).some(k => k.startsWith('source-template/'))).toBe(true);
  expect(strFromU8(zip['LICENSE.txt'])).toContain('Version 3, 29 June 2007');
  const json = JSON.parse(strFromU8(zip[Object.keys(zip).find(k => k.endsWith('.json'))!]));
  expect(json.central.diameter).toBe(65); expect(json.central.print.diameterAllowanceMm).toBe(0.5); expect(json.license).toBe('GPL-3.0-only');
  await page.screenshot({ path: testInfo.outputPath('studio.png'), fullPage: true });
  expect(errors).toEqual([]);
});

test('validation blocks stale exports; edits and undo remain usable', async ({ page }) => {
  await page.goto('./'); await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 60000 });
  await page.getByTestId('accept-warnings').check();
  await page.getByLabel('X 偏移', { exact: true }).first().fill('100');
  await expect(page.getByTestId('export-step')).toBeDisabled();
  await expect(page.getByRole('alert')).toContainText('保护区', { timeout: 30000 });
  await page.getByRole('button', { name: '撤销' }).click();
  await expect(page.getByLabel('X 偏移', { exact: true }).first()).toHaveValue('0');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await page.getByRole('button', { name: 'M 型内螺纹', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('确认');
  await expect(page.getByLabel('螺纹公称外径 D')).toHaveValue('65');
  await page.getByLabel('我已确认实际配合件的外径与螺距').check();
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
});

test('custom lensboard profiles and rear light traps export without an unrelated source template', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('./'); await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 60000 });
  await page.getByTestId('board-source-custom').click();
  await expect(page.getByTestId('custom-board-fields')).toBeVisible();
  await expect(page.getByText('当前外形: 圆角矩形')).toBeVisible();
  await page.getByLabel('镜头板长度', { exact: true }).fill('120');
  await page.getByLabel('镜头板宽度', { exact: true }).fill('80');
  await page.getByLabel('外轮廓圆角半径', { exact: true }).fill('40');
  await expect(page.getByText('当前外形: 跑道形')).toBeVisible();
  await page.getByTestId('outer-light-trap').check(); await page.getByTestId('inner-light-trap').check();
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await expect(page.locator('.metrics-panel')).toContainText('5.00 mm');
  await page.getByLabel('内圈凸台长度', { exact: true }).fill('112');
  await expect(page.getByRole('alert')).toContainText('轮廓范围须满足'); await expect(page.getByTestId('export-step')).toBeDisabled();
  await page.getByLabel('内圈凸台长度', { exact: true }).fill('60');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await page.locator('.relief-panel summary').click(); await page.getByTestId('relief-enabled').check();
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
  await expect(page.locator('.metrics-panel')).toContainText('2.50 mm');
  await page.getByTestId('accept-warnings').check();
  const pending = page.waitForEvent('download'); await page.getByTestId('export-step').click();
  const file = await pending, zip = unzipSync(readFileSync((await file.path())!));
  expect(file.suggestedFilename()).toContain('custom-board-120x80x3-R40');
  expect(Object.keys(zip).some(name => name.startsWith('source-template/'))).toBe(false);
  expect(strFromU8(zip['CUSTOM-BOARD.txt'])).toContain('Rear outer light-trap ring: width 3 mm, height 2 mm');
  const json = JSON.parse(strFromU8(zip[Object.keys(zip).find(k => k.endsWith('.json'))!]));
  expect(json).toMatchObject({ schemaVersion: 5, boardSource: 'custom', relief: { enabled: true }, customBoard: { width: 120, height: 80, thickness: 3, radius: 40, outerLightTrap: { enabled: true }, innerLightTrap: { enabled: true } } });
  await page.getByRole('button', { name: 'EN', exact: true }).click();
  await expect(page.getByText('Current outline: Racetrack')).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('custom-racetrack-light-traps.png'), fullPage: true });
  expect(errors).toEqual([]);
});

test('all thirteen templates load, STL downloads, and invalid JSON preserves the design', async ({ page }, testInfo) => {
  await page.goto('./');
  await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 60000 });
  const templates = page.getByRole('combobox', { name: '镜头板模板', exact: true });
  await expect(templates.locator('option')).toHaveCount(13);
  for (const id of ['horseman-blank', 'horseman-simplified-blank', 'linhof-blank', 'linhof-technika-iii-iv-69-blank', 'graflex-pacemaker45-simplified-blank', 'graflex-pre-anniversary-45-blank', 'rollei-xact2-blank', 'sinar-simplified-blank', 'alpa-blank', 'arca141-blank', 'cambo-twr54-simplified-blank', 'toyo158-simplified-blank', 'sinar-blank']) {
    await templates.selectOption(id);
    await expect(page.getByTestId('model-status')).toContainText('模型已就绪', { timeout: 30000 });
    await expect(page.getByRole('alert')).toHaveCount(0);
  }
  await page.getByTestId('accept-warnings').check();
  const event = page.waitForEvent('download'); await page.getByTestId('export-stl').click();
  const file = await event, path = testInfo.outputPath('model-stl.zip'); await file.saveAs(path);
  const zip = unzipSync(readFileSync(path)), stl = zip[Object.keys(zip).find(k => k.endsWith('.stl'))!];
  expect(stl.length).toBeGreaterThan(84);
  const view = new DataView(stl.buffer, stl.byteOffset, stl.byteLength);
  expect(stl.length).toBe(84 + 50 * view.getUint32(80, true));
  await page.locator('input[type=file]').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"schemaVersion":999}') });
  await expect(page.getByRole('alert')).toContainText('当前设计未被覆盖');
  await expect(templates).toHaveValue('sinar-blank');
  await expect(page.getByTestId('actual-diameter')).toHaveText('34.60 mm');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
